#!/bin/sh
#
# Author: Kayvan Sylvan
#
# Automated rsync+ssh backup from WD My Passport Wireless device
#
cd $(dirname $0)
my_script=$(pwd)/$(basename $0)

usage() { echo "Usage: $0 [setup | doit]"; exit 0; }

proc_exists()
{
  kill -0 $1 2>/dev/null
}

if [ $# -ne 1 ]
then
  usage
  exit 0
fi

# Change these for your setup
#
SRC=192.168.1.101:/DataVolume/
DESTDIR=/DataVolume/Backup/mwp_backup
LOG=/DataVolume/Backup/rsync.log
WHEN="0,30 * * * *" # cron specification (2AM every day)
CRON_INIT=$(ls /etc/init.d/*cron*)
MY_CRON_FILENAME="backup_my_data"
RSYNC_OPTS="-avz -h --progress"

run_command()
{
  proc=$1
  cmdline="$@"
  pidfile=/var/run/"$proc".pid
  if [ -r $pidfile ]
  then
    if proc_exists $(cat $pidfile)
    then
      echo "$proc still running... Not doing anything." >> $LOG
      return 0
    fi
  fi

  $cmdline >> $LOG 2>&1 &
  echo "$!" > $pidfile
  wait $!
}

if [ ! -d $DESTDIR ]; then mkdir $DESTDIR; fi

case "$1" in
setup)
  echo "$WHEN root $my_script doit" > /etc/cron.d/$MY_CRON_FILENAME
  $CRON_INIT restart
  ;;
doit)
  START=$(date)
  echo "About to rsync $SRC to $DESTDIR" >> $LOG
  run_command rsync $RSYNC_OPTS root@$SRC $DESTDIR
  echo "STARTED at $START - ENDED at $(date)" >> $LOG
  ;;
*)
  usage;;
esac
